// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseTools.Models;

public partial class Chatroom
{
    public Guid Id { get; set; }

    public byte ChatroomType { get; set; }

    public DateTime CreateTime { get; set; }
}