// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseTools.Models;

public partial class ChatroomMember
{
    public long UserId { get; set; }

    public Guid ChatroomId { get; set; }

    public DateTime EntryTime { get; set; }
}