// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseTools.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DatabaseTools.Models
{
    public partial interface IChatrommDBContextProcedures
    {
        Task<List<usp_Chatroom_AddResult>> usp_Chatroom_AddAsync(Guid? Id, byte? ChatroomType, DateTime? CreateTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_ChatroomMember_AddResult>> usp_ChatroomMember_AddAsync(Guid? ChatroomId, long? UserId, DateTime? EntryTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_ChatroomMember_GetListResult>> usp_ChatroomMember_GetListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_ChatroomMember_GetListByUserIdResult>> usp_ChatroomMember_GetListByUserIdAsync(long? UesrId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_MessageLog_GetHistoryListResult>> usp_MessageLog_GetHistoryListAsync(Guid? GroupId, long? EndMessageId, int? PageNumber, int? PageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_MessageLog_GetHistoryListCountResult>> usp_MessageLog_GetHistoryListCountAsync(Guid? GroupId, int? EndMessageId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_MessageLog_GetNewMessageListResult>> usp_MessageLog_GetNewMessageListAsync(Guid? GroupId, long? StartId, int? PageNumber, int? PageSize, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_MessageLog_GetNewMessageListCountResult>> usp_MessageLog_GetNewMessageListCountAsync(Guid? GroupId, int? StartId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_MessageLog_GroupTotalCount_GetResult>> usp_MessageLog_GroupTotalCount_GetAsync(Guid? GroupId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_MessageLog_InsertResult>> usp_MessageLog_InsertAsync(Guid? GroupId, long? SendUserId, string Message, DateTime? SendTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_User_GetResult>> usp_User_GetAsync(string Account, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_User_GetListResult>> usp_User_GetListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_User_InsertResult>> usp_User_InsertAsync(string Account, string Password, string UserName, DateTime? CreateTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
