// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DatabaseTools.Models;

public partial class MessageLog
{
    public long Id { get; set; }

    public Guid GroupId { get; set; }

    public byte Status { get; set; }

    public string Message { get; set; }

    public long SendUserId { get; set; }

    public DateTime SendTime { get; set; }
}