// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DatabaseTools.Models
{
    public partial class usp_ChatroomMember_GetListByUserIdResult
    {
        public long UserId { get; set; }
        public Guid ChatroomId { get; set; }
        public DateTime EntryTime { get; set; }
    }
}
